### PR TITLE
feat(home): add legal disclaimer below tools list

### PR DESCRIPTION
**Pull request by arathjz**
**What:**
Add a legal disclaimer to the dispute tools

**Why:**
Closes: https://app.asana.com/0/1159164196409129/1199960314973457/f

**How:**
Add label mentioned in the task description

### Media
image
image
image

### CODE REVIEW

**Comment by duranmla** [comment]
Hey! Sorry for being a pain. I wanted to do this one but I am having hard times to boot the project. In any case, can we:
- Try to use a smaller font? _(most likely using `<small>` which is a bit under `1rem` will be good)_
- Center the text horizontally
- Remove the bold font-weight

While I understand this doesn't have design, legal disclaimers doesn't tend to highlight as part of the whole content but rather a hint of sort of aside comment. This one feels too similar to the main content

**Review by duranmla — CHANGES_REQUESTED** [review]
I would choose less visual hierarchy for this information.

**Comment by orlando** [comment]
Hey @arathjz 

Can you also delete the twitter link on the contact page too please? https://tools.debtcollective.org/contact.
image.

**Comment by arathjz** [comment]
@orlando @duranmla this is ready for review again

**Comment by arathjz** [comment]
@orlando @duranmla changes applied

**Review by orlando — APPROVED** [review]
LGTM!

**Pull request merged**
