### PR TITLE
fix(Field): Prevent fatal error on getAttributesFromValidations

### LINKED ISSUE #117: TypeError: Object doesn't support property or method 'startsWith'
Sentry Issue: [DISPUTE-TOOLS-11](https://sentry.io/debt-collective/dispute-tools/issues/868307353/?referrer=github_integration)

```
TypeError: Object doesn't support property or method 'startsWith'
  at Anonymous function (./lib/data/form-definitions/validations.js:164:7)
  at this (./lib/data/form-definitions/validations.js:163:5)
  at k (./lib/data/form-definitions/validations.js:137:7)
  at Anonymous function (./lib/data/form-definitions/shared-fields/debtAmount.js:5:1)
  at Anonymous function (./lib/data/form-definitions/shared-fields/index.js:1:1)
...
(22 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by duranmla**
The method of getAttributesFromValidations may receive inputs that don't belong to any of the
defined cases within, thus, those cases will throw an unexpected error that makes the whole flow
crash. This commit adds some tests cases to monitor and support unexpected entries.

Closes #117

### CODE REVIEW

**Comment by duranmla** [comment]
Maybe the build is failing cause the new dependency @orlando ?

**Comment by orlando** [comment]
@duranmla no it’s an issue we have with gitlab CI, their shared runners fail with no apparent reason when generation PDFs

**Comment by orlando** [comment]
I retried the rest but this is something we need to invest time into fixing

**Comment by duranmla** [comment]
Well got it, we can leave this until we have the CI running properly, for the record, I mentioned in another comment but the tests are not passing out of the box, there are some extra configuration to do that I can not find documentation of, if you know about it please let me know.

First, the test suite asks for a "dispute_tools_test" db, which then I create manually, nevertheless, it also asks for an admin column but making all those steps manually makes me think that I may be doing something wrong.

**Comment by orlando** [comment]
@duranmla migrations are run when starting the tests, you just need to create the database manually. Check if there an error in the scripts that run migrations

**Pull request merged**
